### ISSUE TITLE
Some source files miss Apache license headers

### ISSUE THREAD

**Issue by daisy-ycguo** [apache/incubator-openwhisk-runtime-python#10]
Following [Apache license header guideline](http://www.apache.org/legal/src-headers.html), **all human-readable Apache-developed files that are included within a distribution must include the header text with few exceptions**. You can find few exceptions here: [which files do not require a license header](http://www.apache.org/legal/src-headers.html#faq-exceptions).

I used Apache Rat to check this repository after excluding a few files, and I got this report. We need to add Apache licensing header to those files.
```
Unapproved licenses:

  openwhisk-runtime-python/core/python2Action/CHANGELOG.md
  openwhisk-runtime-python/core/python2Action/Dockerfile
  openwhisk-runtime-python/core/pythonAction/CHANGELOG.md
  openwhisk-runtime-python/core/pythonAction/Dockerfile
  openwhisk-runtime-python/tests/src/test/resources/application.conf
  openwhisk-runtime-python/ansible/environments/local/group_vars/all
  openwhisk-runtime-python/ansible/environments/local/hosts
```

The excluded files are:
```
**/*.json
**/**.gradle
**/gradlew
**/gradle/**
**/.**
**/templates/**
**/*.j2.*
**/.github/**
**/auth.whisk.system
**/auth.guest
**/i18n_resources.go
```

**Comment by daisy-ycguo** [comment]
I suggest to add below files to excluded list because they are configuration files with few creativity.
```
  openwhisk-runtime-python/tests/src/test/resources/application.conf
  openwhisk-runtime-python/ansible/environments/local/group_vars/all
  openwhisk-runtime-python/ansible/environments/local/hosts
```

**Comment by mrutkows** [comment]
@daisy-ycguo can we close this issue?

**Comment by daisy-ycguo** [comment]
Yes, let's close it. It's good now.
