### ISSUE TITLE
openwhisk/python2action runtime fails with ImportError

### ISSUE THREAD

**Issue by mgencur** [apache/incubator-openwhisk-runtime-python#35]
The Python2 runtime using image openwhisk/python2action:latest fails to start with the following exception in logs:
```
Traceback (most recent call last):
  File "pythonrunner.py", line 26, in <module>
    from actionproxy import ActionRunner, main, setRunner
ImportError: No module named actionproxy
```
The python3 runtime works as expected.

## Steps to reproduce the issue:

1.   wsk action create myAction tests/dat/actions/hello.py --docker openwhisk/python2action:latest 
2.   wsk action invoke myAction --blocking

## Provide the expected results and outputs:

```
{
    "greeting": "Hello stranger!"
}
```

## Provide the actual results and outputs:

```
error: Unable to invoke action 'myAction': The connection failed, or timed out. (HTTP status code 504)
```

**Comment by rabbah** [comment]
I can't reproduce this. What's your docker hash for the openwhisk/python2action you're using - try removing the image locally and pulling it again.

**Comment by rabbah** [comment]
@csantanapr should we add all the openwhisk images to the runtime manifest's `blackboxes` section? There's no reason to treat an action created this way as a blackbox/docker action (but it will be today).

**Comment by csantanapr** [comment]
>@rabbah I guess it will allow any invoker to be use when the action is created in this way since, but the image is whitelisted already and cached at deployment time.

What does this has to do with the issue reported here? `ImportError: No module named actionproxy`

**Comment by rabbah** [comment]
Nothing - not related. Just an observation.

**Comment by csantanapr** [comment]
@rabbah yes good observation 👍

**Comment by csantanapr** [comment]
Was not able to reproduce @mgencur 
```
🐑  $ wsk -i action create myAction tests/dat/actions/hello.py --docker openwhisk/python2action:latest
ok: created action myAction


👻  $ wsk -i action invoke myAction --blocking
ok: invoked /_/myAction with id f807e37abcb0444687e37abcb0e44612
{
    "activationId": "f807e37abcb0444687e37abcb0e44612",
    "annotations": [
        {
            "key": "path",
            "value": "guest/myAction"
        },
        {
            "key": "waitTime",
            "value": 1875
        },
        {
            "key": "kind",
            "value": "blackbox"
        },
        {
            "key": "limits",
            "value": {
                "logs": 10,
                "memory": 256,
                "timeout": 60000
            }
        },
        {
            "key": "initTime",
            "value": 420
        }
    ],
    "duration": 423,
    "end": 1534799891345,
    "logs": [],
    "name": "myAction",
    "namespace": "guest",
    "publish": false,
    "response": {
        "result": {
            "greeting": "Hello stranger!"
        },
        "status": "success",
        "success": true
    },
    "start": 1534799890922,
    "subject": "guest",
    "version": "0.0.1"
}
```
Using the following image
```
🐑  $ docker images | grep openwhisk/python2
openwhisk/python2action latest  34791a3f635d        40 hours ago        299MB
```

**Comment by csantanapr** [comment]
No actionable. unable to reproduce.
Open new issue if new information or steps to reproduce are available.
