### ISSUE TITLE
action proxy is not in this repo

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk-runtime-python#4]
the structure of the runtimes directory is not ideal - the action proxy is currently in the docker runtime repo which means we have to copy it here (wget inside the dockerfile?) to create a new runtime not based on alpine. is there a better way?

**Comment by rabbah** [comment]
in fact, already there's a cloned copy here: https://github.com/ibm-functions/runtime-python3/blob/master/python3/actionproxy.py

all these clones and owns are going to be very painful to maintain - we need to reorganize these before it becomes a mess.

**Comment by csantanapr** [comment]
You mean you prefer to fetch the proxy from docker runtime repo from Dockerfile?

**Comment by csantanapr** [comment]
Closed by https://github.com/apache/incubator-openwhisk-runtime-python/commit/148e57807db83272865711e95ba999978cef2abd
